import { Noto_Sans } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/lib/AuthProvider";

import { cn } from "@/lib/utils";


const notoSans = Noto_Sans({
  subsets: ["latin"],
  variable: "--noto-sans",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          notoSans.variable
        )}
      >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
